[config]
reload_apps = true

[templates.hyprland]
input_path = "/home/yurxi/.config/matugen/templates/hyprland.lua.template"
output_path = "/home/yurxi/.config/hypr/colors.lua"

[templates.alacritty]
input_path = "/home/yurxi/.config/matugen/templates/alacritty-colors.toml.template"
output_path = "/home/yurxi/.cache/matugen/colors.toml"

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini.template'
output_path = '~/.config/cava/colors'

[templates.rofi]
input_path = '/home/yurxi/.config/matugen/templates/rofi-colors.rasi.template'
output_path = '~/.config/rofi/colors.rasi'